### ISSUE TITLE
Publishing ClickOnce project with non-framework build of MSBuild results in error

### ISSUE THREAD

**Issue by tom-bowles** [dotnet/deployment-tools#203]
I have a ClickOnce project that targets net472 and has been migrated to SDK 5. It uses the Publish target with PublishProtocol=ClickOnce. It works in VS but with the dotnet CLI it gives:

`error MSB4062: The "Microsoft.Build.Tasks.GenerateTrustInfo" task could not be loaded from the assembly Microsoft.Build.Tasks.Core, Version=15.1.0.0`

The reason is that the non-framework builds of Microsoft.Build.Tasks.Core indeed are missing that and other tasks. Without them it isn't capable of building ClickOnce manifests.

I understand that there is a "Mage" command line tool that can be used to generate the manifest, but I can't find any information on how to integrate it with the MSBuild Publish target. I'm assuming from the goals stated at https://devblogs.microsoft.com/dotnet/announcing-net-5-0-rc-2/, which include "Enable a modern CI/CD for ClickOnce publishing with command-line flows, with either MSBuild or the Mage tool" and "Our intention has been to enable a parity experience with the existing ClickOnce support for .NET Framework" that I am supposed to be able to do this with SDK 5, so I'm hoping there are some suitable MSBuild tasks I can use.

**Comment by alansingfield** [comment]
Hello Tom,

You can create the manifest files for a .NET 5/6 clickonce project through the command line / powershell; this is how I achieved this:
https://github.com/alansingfield/ClickOncePowershell

MAGE is installed via:
`dotnet tool install microsoft.dotnet.mage`

I create the manifest files as a separate stage in my CI pipeline, rather than having them under the MSBuild Publish target.
This is because I take a single build of the software, then produce different releases with different configuration files included in the ClickOnce deployment.

Add this to your csproj:

```
  <PropertyGroup>
    <!-- Location of Application output artifact -->
    <AppOutputPath>$(ArtifactDir)\App</AppOutputPath>
  </PropertyGroup>

  <!-- Copy application executables -->
  <Target Name="CopyApp" Condition=" '$(ArtifactDir)' != '' " AfterTargets="CopyFilesToOutputDirectory">

    <Exec Command="rd /s /q $(AppOutputPath)" />

    <!-- Always exclude development.json settings files -->
    <CreateItem Include="$(TargetDir)\**\*.*" Exclude="$(TargetDir)\**\*.pdb;$(TargetDir)\**\*.vshost*;$(TargetDir)\**\*Settings.Development.json">
      <Output TaskParameter="Include" ItemName="AppFiles" />
    </CreateItem>

    <Copy SourceFiles="@(AppFiles)" DestinationFiles="@(AppFiles->'$(AppOutputPath)\%(RecursiveDir)%(Filename)%(Extension)')" />

  </Target>
```

In your BUILD pipeline, for the MSBuild command step, add parameters:
/p:ArtifactDir=$(build.artifactstagingdirectory) /p:PublishProfile=WebPublish /p:DeployOnBuild=true 

The BUILD pipeline should have a step to publish the \App folder as an artifact. This will be all your DLLs and EXEs etc.

In the RELEASE pipeline:

- Download the App artifact
- Use a powershell script to amend any configuration JSON files (setting DB connection string based on the release pipeline variables)
- CreateClickOnce.ps1 from https://github.com/alansingfield/ClickOncePowershell

CreateClickOnce.ps1 will create the application manifest files, using the correct SHA256 signatures from AFTER you amended the config files.

A shortcoming of this is that you are running the MAGE tool on the release server, there may be a better way to do this? I'm open to ideas...
