### ISSUE TITLE
Application cannot consume arguments provided in .appref-ms activation

### ISSUE THREAD

**Issue by NikolaMilosavljevic** [dotnet/deployment-tools#236]
For Clickonce deployed .NET FX applications, it is possible to activate the application via `.appref-ms` file and supply additional arguments, like `%userprofile%\Desktop\MyApp.appref-ms arg1,arg2,arg3`

.NET FX application would obtain those arguments using `AppDomain.CurrentDomain.SetupInformation.ActivationArguments.ActivationData[0]`

This experience is not possible in ClickOnce deployed .NET (Core) apps. It is likely due to the use of Launcher, which has access to those arguments, but is not passing them to the app.

See https://github.com/dotnet/deployment-tools/issues/53#issuecomment-1323211688 for more info.

**Comment by davsun55** [comment]
Is it true that there isn't a solution for this?
That is, it is not possible for a Windows .Net7 app deployed with Clickonce, to determine the file that the user double-clicked on which opened the app via a file association. Is this true? And it's been unfixed since .net 5? Really?

**Comment by NikolaMilosavljevic** [comment]
> Is it true that there isn't a solution for this? That is, it is not possible for a Windows .Net7 app deployed with Clickonce, to determine the file that the user double-clicked on which opened the app via a file association. Is this true? And it's been unfixed since .net 5? Really?

Thank you @davsun55 for your interest in ClickOnce for .NET 7. ClickOnce for .NET applications is a lightweight deployment solution that provides the most common subset of features previously available only for .NET FX applications.

The good news is that support for activation arguments is coming very soon in upcoming servicing release (7.0.1) of dotnet-mage tool. This will enable both FileAssociation arguments as well as appref-ms arguments.

**Comment by davsun55** [comment]
Thank you for the quick response. I have an immediate need for this functionality (actually I needed it six months ago). As I am a self taught C# developer (I originally developed in Fortran in the 70s), I'll be keen to see a complete example of a Winforms desktop app getting the file name of what was opened by the user.ThanksDavidOn 6 Dec 2022 14:53, Nikola Milosavljevic ***@***.***> wrote:

Is it true that there isn't a solution for this? That is, it is not possible for a Windows .Net7 app deployed with Clickonce, to determine the file that the user double-clicked on which opened the app via a file association. Is this true? And it's been unfixed since .net 5? Really?

Thank you @davsun55 for your interest in ClickOnce for .NET 7. ClickOnce for .NET applications is a lightweight deployment solution that provides the most common subset of features previously available only for .NET FX applications.
The good news is that support for activation arguments is coming very soon in upcoming servicing release (7.0.1) of dotnet-mage tool. This will enable both FileAssociation arguments as well as appref-ms arguments.

**Comment by NikolaMilosavljevic** [comment]
Fix in PR: https://github.com/dotnet/deployment-tools/pull/245

**Comment by jgbptl** [comment]
> The good news is that support for activation arguments is coming very soon in upcoming servicing release (7.0.1) of dotnet-mage tool. This will enable both FileAssociation arguments as well as appref-ms arguments.

Any news on this (the 7.0.1 release of dotnet-mage)? Would be very useful in a project I am working on...
