### ISSUE TITLE
Clickonce project reference issue

### ISSUE THREAD

**Issue by rkone** [dotnet/deployment-tools#68]
Trying to publish a ClickOnce application with a reference to a class library using an alternate target framework, the referenced framework folder is the same as the main project's framework folder.
For instance, my sample net5.0-windows app adds the reference like so:
/reference:<solution folder>\ClassLibrary1\bin\Release\net5.0-windows\ClassLibrary1.dll 
The actual file is in: \ClassLibrary1\bin\Release\netstandard2.1\ClassLibrary1.dll

Sample solution is at https://github.com/rkone/Net5.0ClickOnceReferenceFailure

**Comment by NikolaMilosavljevic** [comment]
@John-Hart @sujitnayak can you please route this into VS ClickOnce issue and let us know so we can close this issue?

**Comment by John-Hart** [comment]
Thanks @rkone.

I've opened a Visual Studio feedback item to track this: https://developercommunity2.visualstudio.com/t/ClickOnce-Publish-for-NET-Core-31-and-/1275937. I did find a work around was to target a specific runtime instead of using Portable. 

If you find run into any more issues please use the Help >Send Feedback menu in Visual Studio

**Comment by NikolaMilosavljevic** [comment]
Closing in favor of VS Feedback issue.
